apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: application
build:
  artifacts:
  - image: hwchiu/cicd-app
deploy:
  helm:
    releases:
    - name: cicd
      chartPath: helm
      values:
        nginx.image: hwchiu/cicd-app
      imageStrategy:
        helm: {}
      setValues:
        nginx.pullPolicy: IfNotPresent
